spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb+srv://jadhavmanthan33:manthan@cluster0.oesvpam.mongodb.net/fitnessrecommendation
      database: fitnessrecommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

server:
  port: 8083

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}



