spring:
  data:
    mongodb:
      uri: mongodb+srv://jadhavmanthan33:manthan@cluster0.oesvpam.mongodb.net/fitnessapp
      database: fitnessapp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost  # Redis container is mapped to localhost
    port: 6379       # Default Redis port
    password:

server:
  port: 8082


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking



