spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8443/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/user/**
        - id: activityservice
          uri: lb://ACTIVITYSERVICE
          predicates:
            - Path=/api/activities/**
        - id: aiservice
          uri: lb://AISERVICE
          predicates:
            - Path=/api/recommendations/**

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



