spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user
    username: admin
    password : admin123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




